ext_display:
  xplane:
    xpHost: 127.0.0.1
shr_mem:
  crg_lim_io:
    dtype: float64
    name: shm_biolim_data_672
    num: 11
    varnames:
      - airspeed_limit
      - altitude_limit
      - loadfactor_max
      - loadfactor_min
      - climbrate_max
      - climbrate_min
      - roll_angle_limit
      - pitch_angle_limit
      - roll_rate_limit
      - pitch_rate_limit
      - sideforce_max
  joystick_axes_input:
    dtype: float64
    name: shm_JoyStick_axes_672
    num: 8
  joystick_btns_input:
    dtype: bool
    name: shm_JoyStick_btns_672
    num: 32
  joystick_hats_input:
    dtype: int32
    name: shm_JoyStick_hats_672
    num: 16
  sim_io:
    dtype: float64
    name: shm_sim_data_io_672
    num: 65
    varnames:
      - time
      - time_wall
      - u_fps
      - v_fps
      - w_fps
      - p_dps
      - q_dps
      - r_dps
      - roll_deg
      - pitch_deg
      - yaw_deg
      - x_earth_ft
      - y_earth_ft
      - z_earth_ft
      - accx_fps2
      - accy_fps2
      - accz_fps2
      - udot_fps2
      - vdot_fps2
      - wdot_fps2
      - pdot_dps2
      - qdot_dps2
      - rdot_dps2
      - lat_deg
      - lon_deg
      - alt_ft
      - v_north_fps
      - v_east_fps
      - v_down_fps
      - grav_x_fps2
      - grav_y_fps2
      - grav_z_fps2
      - TAS_fps
      - EAS_fps
      - alpha_deg
      - beta_deg
      - mach
      - q_inf_psf
      - oat_degK
      - rho_slft3
      - prs_psf
      - vsnd_fps
      - duct_l_deg
      - duct_r_deg
      - coll_l_deg
      - coll_r_deg
      - cyc_l_deg
      - cyc_r_deg
      - vane_l_deg
      - vane_r_deg
      - bvr_deg
      - prop_l_rpm
      - prop_r_rpm
      - gear_lf_pct
      - gear_lr_pct
      - gear_rf_pct
      - gear_rr_pct
      - alt_agl_ref_ft
      - alt_agl_whl_ft
      - terr_ht_ft
      - terr_nrml_east
      - terr_nrml_north
      - terr_nrml_up
      - over_water
      - terr_freshness
  afd_hitl_io:
    dtype: float64
    name: shm_ares_afd_hitl_data_io_672
    num: 53
    varnames:
      - fr150_RateXCal
      - fr150_RateYCal
      - fr150_RateZCal
      - fr150_AccelXCal
      - fr150_AccelYCal
      - fr150_AccelZCal
      - fr150_StaticPressCal
      - fr150_DynamicPressCal
      - fr150_DeltaPressACal
      - fr150_DeltaPressBCal
      - fr150_OATCal
      - fr152_GPSLat
      - fr152_GPSLong
      - fr152_GPSAlt
      - fr152_GPSVelN
      - fr152_GPSVelE
      - fr152_GPSVelD
      - fr152_GPSTimeLastFix
      - Frame160Freshness
      - Frame160TimeLocalRx
      - Frame160TimeHW
      - fr1_rolrat
      - fr1_pitrat
      - fr1_yawrat
      - fr1_aclx
      - fr1_acly
      - fr1_aclz
      - fr1_rolang
      - fr1_pitang
      - fr1_hdg
      - fr1_veleast
      - fr1_velnorth
      - fr1_velup
      - fr1_lat
      - fr1_lon
      - fr1_altbi
      - fr1_ias
      - fr1_aoa
      - fr1_aos
      - fr1_magfom
      - fr1_status_mode
      - fr1_sts_cbit
      - fr1_sts_acel
      - fr1_sts_gyro
      - fr1_sts_air
      - fr1_sts_baro
      - fr1_sts_mag
      - fr1_wgs84alt
      - fr1_gpstow
      - fr1_hdgerr
      - fr1_oatused
      - Frame1TimeLocalRx
      - Frame1TimeHW
  gcs_uplink:
    dtype: uint8
    name: shm_ares_gcs_uplink_data_672
    num: 40
  gcs_downlink:
    dtype: uint8
    name: shm_ares_gcs_downlink_data_672
    num: 245
  hitl_can_spy_io:
    dtype: float64
    name: shm_ares_afd_hitl_can_spy_io_672
    num: 52
    varnames:
      - freshness
      - fcc_portfwd_cmd_in
      - fcc_portaft_cmd_in
      - fcc_portvane_cmd_in
      - fcc_stbdfwd_cmd_in
      - fcc_stbdaft_cmd_in
      - fcc_stbdvane_cmd_in
      - fcc_bvr_cmd_in
      - fcc_portisa_cmd_in
      - fcc_stbdisa_cmd_in
      - fcc_pla_fwd_eng_deg
      - fcc_pla_aft_eng_deg
      - fcc_cp_fwd_eng_deg
      - fcc_cp_aft_eng_deg
      - acm1a_portfwd_cmdrb_in
      - acm1b_portfwd_cmdrb_in
      - acm2a_portaft_cmdrb_in
      - acm2b_portaft_cmdrb_in
      - acm3a_portvane_cmdrb_in
      - acm3b_portvane_cmdrb_in
      - acm4a_stbdfwd_cmdrb_in
      - acm4b_stbdfwd_cmdrb_in
      - acm5a_stbdaft_cmdrb_in
      - acm5b_stbdaft_cmdrb_in
      - acm6a_stbdvane_cmdrb_in
      - acm6b_stbdvane_cmdrb_in
      - acm7a_bvr_cmdrb_in
      - acm8a_portisa_cmdrb_in
      - acm8b_stbdisa_cmdrb_in
      - acm9a_portisa_cmdrb_in
      - acm9b_stbdisa_cmdrb_in
      - acm10a_portisa_cmdrb_in
      - acm10b_stbdisa_cmdrb_in
      - acm1a_portfwd_pos_in
      - acm1b_portfwd_pos_in
      - acm2a_portaft_pos_in
      - acm2b_portaft_pos_in
      - acm3a_portvane_pos_in
      - acm3b_portvane_pos_in
      - acm4a_stbdfwd_pos_in
      - acm4b_stbdfwd_pos_in
      - acm5a_stbdaft_pos_in
      - acm5b_stbdaft_pos_in
      - acm6a_stbdvane_pos_in
      - acm6b_stbdvane_pos_in
      - acm7a_bvr_pos_in
      - acm8a_portisa_pos_in
      - acm8b_stbdisa_pos_in
      - acm9a_portisa_pos_in
      - acm9b_stbdisa_pos_in
      - acm10a_portisa_pos_in
      - acm10b_stbdisa_pos_in
